Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = true
LastUsedInput = "alsa_input.pci-0000_00_1f.3.analog-stereo"
LastUsedOutput = "alsa_output.pci-0000_00_1f.3.analog-stereo"
